// import { QuestionCardProps } from "@/types/questions.types";

// export const questions: QuestionCardProps[] = [
//     {
//         title: "Wprowadzenie do TypeScript",
//         createdAt: "2025-05-25",
//         likes: 34,
//         unlikes: 2,
//         answers: 12,
//         shares: 5,
//         views: 450,
//         author: {
//             id: "1",
//             name: "devAnna",
//             avatarUrl: "https://i.pravatar.cc/40?img=1",
//             bio: "Pasja do TypeScript i frontend developmentu",
//             role: "Frontend Developer",
//             createdAt: "2023-01-10",
//             answersCount: 120,
//             questionsCount: 40,
//             reputation: 512,
//         },
//     },
//     {
//         title: "Jak efektywnie korzystać z React Hooks",
//         createdAt: "2025-05-28",
//         likes: 56,
//         unlikes: 1,
//         answers: 22,
//         shares: 8,
//         views: 1200,
//         author: {
//             id: "2",
//             name: "reactMaster",
//             avatarUrl: "https://i.pravatar.cc/40?img=2",
//             bio: "Ekspert w React i nowoczesnym JS",
//             role: "Senior React Developer",
//             createdAt: "2021-06-12",
//             answersCount: 210,
//             questionsCount: 55,
//             reputation: 1220,
//         },
//     },
//     {
//         title: "Node.js – podstawy budowy serwera",
//         createdAt: "2025-05-20",
//         likes: 45,
//         unlikes: 3,
//         answers: 15,
//         shares: 4,
//         views: 800,
//         author: {
//             id: "3",
//             name: "nodeGuru",
//             avatarUrl: "https://i.pravatar.cc/40?img=3",
//             bio: "Backendowiec specjalizujący się w Node.js",
//             role: "Backend Developer",
//             createdAt: "2022-02-28",
//             answersCount: 134,
//             questionsCount: 29,
//             reputation: 910,
//         },
//     },
//     {
//         title: "CSS Grid vs Flexbox – kiedy co wybrać?",
//         createdAt: "2025-05-22",
//         likes: 38,
//         unlikes: 0,
//         answers: 18,
//         shares: 7,
//         views: 670,
//         author: {
//             id: "4",
//             name: "cssWizard",
//             avatarUrl: "https://i.pravatar.cc/40?img=4",
//             bio: "Frontend developer i designer UI/UX",
//             role: "UI/UX Designer",
//             createdAt: "2023-04-15",
//             answersCount: 89,
//             questionsCount: 21,
//             reputation: 650,
//         },
//     },
//     {
//         title: "Debugowanie aplikacji w Visual Studio Code",
//         createdAt: "2025-05-29",
//         likes: 27,
//         unlikes: 1,
//         answers: 8,
//         shares: 3,
//         views: 400,
//         author: {
//             id: "5",
//             name: "vscoder",
//             avatarUrl: "https://i.pravatar.cc/40?img=5",
//             bio: "Zapalony debugger i fan VS Code",
//             role: "Developer Tools Specialist",
//             createdAt: "2023-08-20",
//             answersCount: 72,
//             questionsCount: 19,
//             reputation: 480,
//         },
//     },
//     {
//         title: "Wprowadzenie do GraphQL",
//         createdAt: "2025-05-23",
//         likes: 42,
//         unlikes: 1,
//         answers: 14,
//         shares: 5,
//         views: 900,
//         author: {
//             id: "6",
//             name: "graphqlFan",
//             avatarUrl: "https://i.pravatar.cc/40?img=8",
//             bio: "Zafascynowany GraphQL i API",
//             role: "Fullstack Developer",
//             createdAt: "2022-11-02",
//             answersCount: 105,
//             questionsCount: 30,
//             reputation: 870,
//         },
//     },
//     {
//         title: "Podstawy testowania jednostkowego w Jest",
//         createdAt: "2025-05-26",
//         likes: 30,
//         unlikes: 0,
//         answers: 10,
//         shares: 3,
//         views: 550,
//         author: {
//             id: "7",
//             name: "jestTester",
//             avatarUrl: "https://i.pravatar.cc/40?img=9",
//             bio: "Tester z pasją do Jest i TDD",
//             role: "QA Engineer",
//             createdAt: "2023-03-17",
//             answersCount: 98,
//             questionsCount: 22,
//             reputation: 720,
//         },
//     },
//     {
//         title: "Tworzenie REST API w Express",
//         createdAt: "2025-05-18",
//         likes: 50,
//         unlikes: 4,
//         answers: 20,
//         shares: 6,
//         views: 1100,
//         author: {
//             id: "8",
//             name: "expressDev",
//             avatarUrl: "https://i.pravatar.cc/40?img=6",
//             bio: "Backendowiec Node.js i Express",
//             role: "Backend Developer",
//             createdAt: "2021-09-11",
//             answersCount: 175,
//             questionsCount: 41,
//             reputation: 1130,
//         },
//     },
//     {
//         title: "Optymalizacja wydajności w React",
//         createdAt: "2025-05-27",
//         likes: 60,
//         unlikes: 2,
//         answers: 25,
//         shares: 10,
//         views: 1500,
//         author: {
//             id: "9",
//             name: "perfReact",
//             avatarUrl: "https://i.pravatar.cc/40?img=7",
//             bio: "Optymalizuję aplikacje React",
//             role: "Frontend Developer",
//             createdAt: "2022-07-04",
//             answersCount: 142,
//             questionsCount: 33,
//             reputation: 980,
//         },
//     },
//     {
//         title: "GraphQL - co to takiego?",
//         createdAt: "2025-05-23",
//         likes: 42,
//         unlikes: 1,
//         answers: 14,
//         shares: 5,
//         views: 900,
//         author: {
//             id: "6",
//             name: "graphqlFan",
//             avatarUrl: "https://i.pravatar.cc/40?img=8",
//             bio: "Zafascynowany GraphQL i API",
//             role: "Fullstack Developer",
//             createdAt: "2022-11-02",
//             answersCount: 105,
//             questionsCount: 30,
//             reputation: 870,
//         },
//     },
//     {
//         title: "Jak wycentrować DIV w HTML?",
//         createdAt: "2025-05-26",
//         likes: 30,
//         unlikes: 0,
//         answers: 10,
//         shares: 3,
//         views: 550,
//         author: {
//             id: "7",
//             name: "jestTester",
//             avatarUrl: "https://i.pravatar.cc/40?img=9",
//             bio: "Tester z pasją do Jest i TDD",
//             role: "QA Engineer",
//             createdAt: "2023-03-17",
//             answersCount: 98,
//             questionsCount: 22,
//             reputation: 720,
//         },
//     },
//     {
//         title: "Deploy aplikacji na Vercel",
//         createdAt: "2025-05-24",
//         likes: 48,
//         unlikes: 1,
//         answers: 16,
//         shares: 7,
//         views: 1000,
//         author: {
//             id: "10",
//             name: "deployPro",
//             avatarUrl: "https://i.pravatar.cc/40?img=10",
//             bio: "Ekspert w deploymencie aplikacji",
//             role: "DevOps Engineer",
//             createdAt: "2021-12-05",
//             answersCount: 115,
//             questionsCount: 27,
//             reputation: 890,
//         },
//     },
// ];
