import { TaskInterface } from "@/types/searchAndFilters.types";

export const TASKS: TaskInterface[] = [
    {
        id: "task-001",
        title: "Stwórz komponent przycisku w React",
        description:
            "Zaprojektuj i zaimplementuj prosty komponent przycisku z obsługą zdarzeń `onClick`, wykorzystując React i TypeScript.",
        points: 50,
        difficulty: "easy",
        tags: ["React", "TypeScript"],
        category: "frontend",
        status: "available",
        createdAt: "2025-06-01T08:00:00Z",
        updatedAt: "2025-06-01T08:00:00Z",
        estimatedTimeMinutes: 15,
        rewardDescription: "+50 punktów doświadczenia",
    },
    {
        id: "task-002",
        title: "Zaimplementuj API do tworzenia użytkownika",
        description:
            "Zbuduj endpoint w Node.js/Express, który pozwala na rejestrację nowego użytkownika. Waliduj dane wejściowe i zapisuj dane w pamięci lub mockowej bazie danych.",
        points: 70,
        difficulty: "medium",
        tags: ["Node.js", "Express", "API"],
        category: "backend",
        status: "available",
        createdAt: "2025-06-02T09:00:00Z",
        updatedAt: "2025-06-02T09:00:00Z",
        estimatedTimeMinutes: 30,
        rewardDescription: "+70 punktów + odznaka Backend Start",
    },
    {
        id: "task-003",
        title: "Zintegruj Prism.js do kolorowania składni",
        description:
            "Dodaj obsługę kolorowania składni do edytora kodu przy użyciu Prism.js. Upewnij się, że obsługiwane są popularne języki jak JavaScript, Python i HTML.",
        points: 100,
        difficulty: "medium",
        tags: ["Prism.js", "highlight", "frontend"],
        category: "frontend",
        status: "locked",
        createdAt: "2025-06-01T10:00:00Z",
        updatedAt: "2025-06-03T12:00:00Z",
        estimatedTimeMinutes: 45,
        prerequisites: ["task-001"],
        rewardDescription: "+100 punktów + Odblokowano zadania zaawansowane",
    },
    {
        id: "task-004",
        title: "Dodaj paginację do listy pytań",
        description:
            "Zaimplementuj paginację po stronie frontend i backend dla listy pytań. Strona powinna umożliwiać przechodzenie do kolejnych stron oraz pokazywać aktualny zakres.",
        points: 90,
        difficulty: "hard",
        tags: ["pagination", "React", "API"],
        category: "fullstack",
        status: "available",
        createdAt: "2025-06-05T10:00:00Z",
        updatedAt: "2025-06-05T10:00:00Z",
        estimatedTimeMinutes: 60,
    },
    {
        id: "task-005",
        title: "Dzienny challenge: odpowiedz na 3 pytania",
        description:
            "Weź udział w życiu społeczności – odpowiedz na co najmniej 3 pytania użytkowników w ciągu jednego dnia.",
        points: 120,
        difficulty: "easy",
        tags: ["community", "daily", "engagement"],
        category: "general",
        status: "available",
        createdAt: "2025-06-11T00:00:00Z",
        updatedAt: "2025-06-11T00:00:00Z",
        isDaily: true,
        rewardDescription: "+120 punktów + Odznaka Aktywny Pomocnik",
    },
];
