import RightSidebar from "@/components/layout/Sidebar/RightSidebar";
import { HeroUIProvider, ToastProvider } from "@heroui/react";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider } from "context/LeftSidebarContext";
import LeftSidebar from "@/components/layout/Sidebar/LeftSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const clerkAppearance = {
    layout: {},
    elements: {},
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <ClerkProvider appearance={clerkAppearance}>
            <html lang="en" suppressHydrationWarning className="dark">
                <body className={`${inter.className} flex flex-col `}>
                    <HeroUIProvider>
                        <ToastProvider placement={"bottom-right"} />
                        <SidebarProvider>
                            <Navbar />
                            <div className="relative flex size-full ">
                                {/* <Sidebar /> */}
                                <aside>
                                    <LeftSidebar />
                                </aside>
                                <main className=" flex-1 px-6 pb-16 pt-[120px] text-cTextDark-100">{children}</main>
                                <RightSidebar />
                            </div>
                        </SidebarProvider>
                    </HeroUIProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
