import RightSidebar from "@/components/layout/Sidebar/RightSidebar";
import { HeroUIProvider, ToastProvider } from "@heroui/react";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import { SidebarProvider } from "context/LeftSidebarContext";
import LeftSidebar from "@/components/layout/Sidebar/LeftSidebar";
import { AuthProvider } from "context/useAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning className="dark">
            <body className={`${inter.className} flex flex-col `}>
                <HeroUIProvider>
                    <ToastProvider placement={"bottom-right"} />
                    <AuthProvider>
                        <SidebarProvider>
                            <Navbar />
                            <div className="relative flex size-full ">
                                {/* <Sidebar /> */}
                                <aside>
                                    <LeftSidebar />
                                </aside>
                                <main className="w-full flex-1 px-6 pb-16 pt-[120px] text-cTextDark-100">
                                    {children}
                                </main>
                                <RightSidebar />
                            </div>
                        </SidebarProvider>
                    </AuthProvider>
                </HeroUIProvider>
            </body>
        </html>
    );
}
